### ISSUE TITLE
Add new input field for NewUser 

### ISSUE THREAD

**Issue by superspike7** [eefborromeo/banking-app#31]
we already had properties of `name`,`id`, and `balance`

we now need to add new input fields for `email` and `password`

and for the `expenseItems` we will just initialize it with and empty array

roughly will look like this:
```
  const user = {
    id: users.length + 1,
    name: name,
    balance: balance,
    email: email, // new email input
    expenseItems: []
  };

```

**Comment by eefborromeo** [comment]
Redundant
